#%RAML 1.0

title: Trial Period API

types:
  Trial: !include /trial.raml

traits:
  secured:
    queryParameters:
      access_token:
        description: The token to get authorized
        type: string

/users/{userId}/trials:
  get:
    is: [ secured ]
    description:
    queryParameters:
      status:
        type: string
    responses:
      200:
        body:
          application/json:
            type: Trial[]
  post:
    description: Creates a new trial period.
    is: [ secured ]
    body:
      application/json:
        type: Trial

  /{trialId}:
    get:
    post: