#%RAML 1.0

title: AeQ Admins
version: v1

types:
  user:           !include types/user.raml
  trial:          !include types/trial.raml
  trialPost:      !include types/trial-post.raml
  trialVote:      !include types/trial-vote.raml
  trialVotePost:  !include types/trial-vote-post.raml

traits:
  secured: !include traits/secured.raml


/trials:
  get:
    is: [ secured ]
    description: Returns a list trials.
    queryParameters:
      status:
        description:
        type: string
    responses:
      200:
        body:
          application/json:
            type: trial
  /{trialId}:
      get:
        is: [ secured ]
        description: Returns a single trial with the given id for this user.
        queryParameters:
          status:
            type: string
        responses:
          200:
            body:
              application/json:
                type: trial
          404:
            body:
              application/json:
                example: |
                  { "message": "trial not found" }

      /votes:
        get:
          is: [ secured ]
          description: Returns a list of votes
          responses:
            200:
              body:
                application/json:
                  type: trialVote[]
        post:
          is: [ secured ]
          description: Creates a new vote
          body:
            application/json:
              type: trialVotePost
          responses:
            200:
            400:
              description: If the user already submitted a vote

        /{voteId}:
          get:
            is: [ secured ]
            description: Returns a single votes.
            responses:
              200:
                body:
                  application/json:
                    type: trialVote
              404:
          put:
            is: [ secured ]
            description: Updates an existing vote
            body:
              application/json:
                type: trialVotePost
            responses:
              200:
              400:
                description: If the user did not submit a vote before
              404:
          delete:
            is: [ secured ]
            description: Deletes a vote
            responses:
              200:
              404:

/users/{userId}/trials:
  get:
    is: [ secured ]
    description: Returns a list of trials for this user.
    queryParameters:
      status:
        description:
        type: string
    responses:
      200:
        body:
          application/json:
            type: trial[]
  post:
    description: Creates a new trial period.
    is: [ secured ]
    responses:
      200:
        description: If the trial has been created successfully.
      400:
        description: If the trial cannot be created.
        body:
          application/json:
            examples:
              TrialAlreadyStarted: !include examples/trial-already-started.json
              TrialBlocked: !include examples/trial-blocked.json





